# Generated by Django 3.2.15 on 2022-09-10 07:55

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DollarRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('rate', models.FloatField(verbose_name='Стоимость')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(verbose_name='Номер заказа')),
                ('dollar_cost', models.IntegerField(validators=[orders.models.validate_positive_number], verbose_name='Стоимость, $')),
                ('ruble_cost', models.IntegerField(blank=True, validators=[orders.models.validate_positive_number], verbose_name='Стоимость, руб')),
                ('delivery_time', models.DateTimeField(verbose_name='Срок поставки')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateTableInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(verbose_name='Последнее время обновления')),
            ],
        ),
    ]
