# Generated by Django 3.2.15 on 2022-09-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_ruble_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateField(verbose_name='Срок поставки'),
        ),
    ]
